// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: books.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (title, author_id, description)
VALUES ($1, $2, $3)
RETURNING id, title, author_id, description
`

type CreateBookParams struct {
	Title       string      `json:"title"`
	AuthorID    int64       `json:"author_id"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook, arg.Title, arg.AuthorID, arg.Description)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Description,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, title, author_id, description FROM books
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBook(ctx context.Context, id int32) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Description,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT 
  books.id, books.title, books.author_id, books.description,
  authors.name AS author_name
  FROM books
JOIN authors ON books.author_id = authors.id
ORDER BY books.id
LIMIT $1
OFFSET $2
`

type ListBooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListBooksRow struct {
	ID          int32       `json:"id"`
	Title       string      `json:"title"`
	AuthorID    int64       `json:"author_id"`
	Description pgtype.Text `json:"description"`
	AuthorName  string      `json:"author_name"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]ListBooksRow, error) {
	rows, err := q.db.Query(ctx, listBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBooksRow{}
	for rows.Next() {
		var i ListBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AuthorID,
			&i.Description,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
  SET title = $2,
      author_id = $3,
      description = $4
WHERE id = $1
RETURNING id, title, author_id, description
`

type UpdateBookParams struct {
	ID          int32       `json:"id"`
	Title       string      `json:"title"`
	AuthorID    int64       `json:"author_id"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBook,
		arg.ID,
		arg.Title,
		arg.AuthorID,
		arg.Description,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Description,
	)
	return i, err
}
