// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64       `json:"id"`
	Name string      `json:"name"`
	Bio  pgtype.Text `json:"bio"`
}

type Book struct {
	ID          int32       `json:"id"`
	Title       string      `json:"title"`
	AuthorID    int64       `json:"author_id"`
	Description pgtype.Text `json:"description"`
}

type User struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Emai     string `json:"emai"`
	Password string `json:"password"`
}
